% Copyright © 2013 Alexey Mednikov, Valeriy Streltsov
% This work is free. You can redistribute it and/or modify it under the
% terms of the Do What The Fuck You Want To Public License, Version 2,
% as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.

\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{G2-105}[2013/05/22 v1.0 Non Standard LaTeX document class]

\input{GostBase.clo}
\RequirePackage[a4paper,left=30mm,right=20mm,top=20mm,bottom=20mm,headsep=0pt]{geometry}
\RequirePackage{G2-105}
\onehalfspacing

\endinput
% End of file `G2-105.cls'.
